//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Almacenamiento
    {
        public int ID_Almacenamiento { get; set; }
        public string Nombre { get; set; }
        public string Path_Almacenamiento { get; set; }
    }
}
