//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEnd.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Libro
    {
        
        public string ID_Libro { get; set; }
        public Nullable<int> Genero_Libro { get; set; }
        [Display(Name = "Nombre")]
        public string Nombre_Libro { get; set; }
        public Nullable<int> Autor_Libro { get; set; }
        public Nullable<int> Idioma_Libro { get; set; }
        public Nullable<int> Editorial_Libro { get; set; }
        [Display(Name = "Año")]
        public int Ano_Libro { get; set; }
        [Display(Name = "Descarga")]
        public string Archivo_Descarga_Libros { get; set; }
        [Display(Name = "Preview")]
        public string Archivo_Previsualizacion_Libro { get; set; }
    
        public virtual Autor Autor { get; set; }
        public virtual Editorial Editorial { get; set; }
        public virtual Genero Genero { get; set; }
        public virtual Idioma Idioma { get; set; }
    }
}
