//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEnd.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Musica
    {
        public string ID_Musica { get; set; }
        public Nullable<int> Genero_Musica { get; set; }
        [Display(Name = "Nombre")]
        public string Nombre_Musica { get; set; }
        [Display(Name = "Tipo Interpretacion")]
        public string Tipo_Inerpretacion_Musica { get; set; }
        public Nullable<int> Idioma_Musica { get; set; }
        public Nullable<int> Pais_Musica { get; set; }
        public Nullable<int> Disquera_Musica { get; set; }
        public Nullable<int> Disco_Musica { get; set; }
        [Display(Name = "Año")]
        public int Ano_Musica { get; set; }
        [Display(Name = "Descarga")]
        public string Archivo_Descarga_Musica { get; set; }
        [Display(Name = "Preview")]
        public string Archivo_Previsualizacion_Musica { get; set; }
    
        public virtual Disco Disco { get; set; }
        public virtual Disquera Disquera { get; set; }
        public virtual Genero Genero { get; set; }
        public virtual Idioma Idioma { get; set; }
        public virtual Pai Pai { get; set; }
    }
}
